
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 13.4 EDK_O.87xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2011 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_LCD_DEVICE_ID,
		XPAR_LCD_BASEADDR,
		XPAR_LCD_INTERRUPT_PRESENT,
		XPAR_LCD_IS_DUAL
	},
	{
		XPAR_PWM_FREQ_DEVICE_ID,
		XPAR_PWM_FREQ_BASEADDR,
		XPAR_PWM_FREQ_INTERRUPT_PRESENT,
		XPAR_PWM_FREQ_IS_DUAL
	},
	{
		XPAR_PWM_VALUE_DEVICE_ID,
		XPAR_PWM_VALUE_BASEADDR,
		XPAR_PWM_VALUE_INTERRUPT_PRESENT,
		XPAR_PWM_VALUE_IS_DUAL
	},
	{
		XPAR_SADC_IN_DEVICE_ID,
		XPAR_SADC_IN_BASEADDR,
		XPAR_SADC_IN_INTERRUPT_PRESENT,
		XPAR_SADC_IN_IS_DUAL
	},
	{
		XPAR_SADC_OUT_DEVICE_ID,
		XPAR_SADC_OUT_BASEADDR,
		XPAR_SADC_OUT_INTERRUPT_PRESENT,
		XPAR_SADC_OUT_IS_DUAL
	},
	{
		XPAR_TPU_CTRL_DEVICE_ID,
		XPAR_TPU_CTRL_BASEADDR,
		XPAR_TPU_CTRL_INTERRUPT_PRESENT,
		XPAR_TPU_CTRL_IS_DUAL
	},
	{
		XPAR_TPU_STS_DEVICE_ID,
		XPAR_TPU_STS_BASEADDR,
		XPAR_TPU_STS_INTERRUPT_PRESENT,
		XPAR_TPU_STS_IS_DUAL
	},
	{
		XPAR_TPU_VALUE_DEVICE_ID,
		XPAR_TPU_VALUE_BASEADDR,
		XPAR_TPU_VALUE_INTERRUPT_PRESENT,
		XPAR_TPU_VALUE_IS_DUAL
	}
};


